# SPDX-FileCopyrightText: 2025 Contributors to the Media eXchange Layer project.
# SPDX-License-Identifier: Apache-2.0
name: Backport merged PRs
on:
  pull_request_target:
    types: [closed, labeled]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  # These jobs are triggered when a PR is closed. The second job will only run when the first job
  # finds labels matching: backport/.*
  inspect:
    name: "Process PR labels"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && (github.event.action == 'closed' || (github.event.action == 'labeled' && startsWith(github.event.label.name, 'backport/')))
    outputs:
      target-branches: ${{ steps.target-branches.outputs.target-branches }}
    steps:
      - name: Parse labels
        id: target-branches
        # this line produces an output like: `target-branches=["release/v1.0.0","release/v1.1.0"]` or `target-branches=[]`
        run: printf 'target-branches=%s\n' "$(echo -e "${{ ((github.event.action == 'closed') && join(github.event.pull_request.labels.*.name, '\n')) || github.event.label.name }}" | sed -nE 's%backport/(.*)%\"release/\1\"%p' | jq -cs '.')" >>"${GITHUB_OUTPUT}"
  backport:
    name: "Create backport PR"
    runs-on: ubuntu-latest
    needs: inspect
    if: ${{ needs.inspect.outputs.target-branches != '[]' }} # Don't run if no backport/* labels were found by the prev. job
    strategy:
      matrix:
        target-branch: ${{ fromJSON(needs.inspect.outputs.target-branches) }}
    steps:
      - name: "Get app token"
        id: token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.BACKPORT_APP_ID }}
          private-key: ${{ secrets.BACKPORT_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          # This should set up the git cli to use the PAT created from the app in the 'token' job
          token: ${{ steps.token.outputs.token }}
      - name: Create backport pull requests
        uses: korthout/backport-action@v4
        with:
          github_token: ${{ steps.token.outputs.token }}
          label_pattern: a^ # We don't need the action to match the labels, we have done that in the prev. job, so we use the pattern 'a^' that never matches anything.
          target_branches: ${{ matrix.target-branch }} # We pass the branches here instead of relying on the label matching logic of the imported action.
          branch_name: backport/${pull_number}/-/${target_branch}
          copy_assignees: true
          copy_requested_reviewers: true
          git_committer_name: backport-bot
          git_committer_email: backport-bot@ebu.ch
          pull_description: 'Backport of #${pull_number} to `${target_branch}`.'
          pull_title: '[Backport to ${target_branch}] ${pull_title}'
          add_labels: 'backport,automation'
